=begin
If we list all the natural numbers below 10 that are multiples of 3 or 5, 
we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000. 
Answer: 233168
=end
def problem1(number)
  sum = 0
  count = 0
  while count < number
  	if (count%3 == 0 || count%5 == 0)
  	  sum += count
  	end
  	count += 1
  end 
  puts sum
end

problem1(1000)

=begin
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...   By considering the terms in the 
Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. Answer: 4613732
=end
def problem2(number)
  firstNumber = 1
  secondNumber = 2
  nextFibonacci = firstNumber + secondNumber
  sum = 0
  if secondNumber < number
  	sum += secondNumber
  end
  while nextFibonacci < number
  	if nextFibonacci%2 == 0
      sum += nextFibonacci
  	end
  	firstNumber = secondNumber
  	secondNumber = nextFibonacci
  	nextFibonacci = firstNumber + secondNumber
  end
  puts sum
end

problem2(4_000_000)

=begin
Problem 3: Largest prime factor
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?
=end
def isPrime(number)
  prime = true
  for check in 2..(number-1)
    if number%check == 0
      prime = false
    end
  end
  return prime
end
def problem3(number)
  largest = 1
  for x in 2..(number) 
    if (isPrime(x) && number%x == 0)
      largest = x
    end
  end
  puts largest
end

problem3(13195)
problem3(100000)
